-- Launch RLS hardening follow-up.
-- Keeps client-side writes narrow after the Supabase Auth migration.

-- Notifications are only created by trusted server code or database triggers.
DROP POLICY IF EXISTS "System can insert notifications" ON public.notifications;
DROP POLICY IF EXISTS "Service role inserts notifications" ON public.notifications;
CREATE POLICY "Service role inserts notifications"
  ON public.notifications FOR INSERT
  WITH CHECK (false);

-- Feed entries are generated by SECURITY DEFINER triggers, not arbitrary clients.
DROP POLICY IF EXISTS "community_feed_insert_trigger" ON public.community_feed;
DROP POLICY IF EXISTS "Service role inserts community feed" ON public.community_feed;
CREATE POLICY "Service role inserts community feed"
  ON public.community_feed FOR INSERT
  WITH CHECK (false);

-- Organization membership mutation is limited to organization admins/founders.
DROP POLICY IF EXISTS "Members can update own membership, admins can update any" ON public.organization_members;
DROP POLICY IF EXISTS "Admins can update organization members" ON public.organization_members;
CREATE POLICY "Admins can update organization members"
  ON public.organization_members FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.organization_members AS actor
      WHERE actor.organization_id = organization_members.organization_id
        AND actor.user_id = requesting_user_id()
        AND actor.membership_status = 'active'
        AND actor.role IN ('gründer', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.organization_members AS actor
      WHERE actor.organization_id = organization_members.organization_id
        AND actor.user_id = requesting_user_id()
        AND actor.membership_status = 'active'
        AND actor.role IN ('gründer', 'admin')
    )
  );

DROP POLICY IF EXISTS "Members can leave, admins can remove" ON public.organization_members;
DROP POLICY IF EXISTS "Admins can delete organization members" ON public.organization_members;
CREATE POLICY "Admins can delete organization members"
  ON public.organization_members FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.organization_members AS actor
      WHERE actor.organization_id = organization_members.organization_id
        AND actor.user_id = requesting_user_id()
        AND actor.membership_status = 'active'
        AND actor.role IN ('gründer', 'admin')
    )
  );

-- Invites are admin/founder-only and must be attributed to the acting user.
DROP POLICY IF EXISTS "Admins can create invites" ON public.organization_invites;
CREATE POLICY "Admins can create invites"
  ON public.organization_invites FOR INSERT
  WITH CHECK (
    invited_by = requesting_user_id()
    AND EXISTS (
      SELECT 1
      FROM public.organization_members AS actor
      WHERE actor.organization_id = organization_invites.organization_id
        AND actor.user_id = requesting_user_id()
        AND actor.membership_status = 'active'
        AND actor.role IN ('gründer', 'admin')
    )
  );

DROP POLICY IF EXISTS "Admins can revoke invites" ON public.organization_invites;
CREATE POLICY "Admins can revoke invites"
  ON public.organization_invites FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.organization_members AS actor
      WHERE actor.organization_id = organization_invites.organization_id
        AND actor.user_id = requesting_user_id()
        AND actor.membership_status = 'active'
        AND actor.role IN ('gründer', 'admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.organization_members AS actor
      WHERE actor.organization_id = organization_invites.organization_id
        AND actor.user_id = requesting_user_id()
        AND actor.membership_status = 'active'
        AND actor.role IN ('gründer', 'admin')
    )
  );

DROP POLICY IF EXISTS "Admins can delete invites" ON public.organization_invites;
CREATE POLICY "Admins can delete invites"
  ON public.organization_invites FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.organization_members AS actor
      WHERE actor.organization_id = organization_invites.organization_id
        AND actor.user_id = requesting_user_id()
        AND actor.membership_status = 'active'
        AND actor.role IN ('gründer', 'admin')
    )
  );
